/**
 * @file config.h
 * Global product configuration.
 */
#ifndef CONFIG_H__
#define CONFIG_H__

#define CONFIG_NVS_NAMESPACE "saihub"

/* Temporary WiFi seed (first flash only; live creds persist in NVS) */
#define CONFIG_WIFI_SSID "CHANGE_ME"
#define CONFIG_WIFI_PASSWORD "CHANGE_ME"
#define CONFIG_WIFI_RECONNECT_INTERVAL_MS 3000
#define CONFIG_WIFI_PORTAL_URL "http://192.168.4.1/wifi/page"

#define CONFIG_NTP_SERVER "pool.ntp.org"
#define CONFIG_NTP_TIMEOUT_MS (15 * 1000)

/* Set to the deployed worker origin, e.g. wss://saihub-cloud.example.workers.dev. */
#define CONFIG_CLOUD_URL "ws://192.168.88.190:8787"
#define CONFIG_CLOUD_MAX_MESSAGE_BYTES (72 * 1024)

#define CONFIG_LOCK_TTL_US (30ULL * 1000 * 1000)
#define CONFIG_LOCK_MAX_COUNT 16
#define CONFIG_LOCK_MAX_RESOURCES 16
#define CONFIG_LOCK_MAX_PERIPHERAL 8

#define CONFIG_GPIO_TRACE_MAX_DURATION_US (60ULL * 1000 * 1000)
#define CONFIG_GPIO_TRACE_MAX_EVENTS 1024
#define CONFIG_GPIO_PULSE_MAX_WIDTH_US (1ULL * 1000 * 1000)
#define CONFIG_GPIO_PWM_MAX_OUTPUTS 4
#define CONFIG_GPIO_PWM_MAX_FREQ_HZ 50000U
#define CONFIG_GPIO_PWM_DEFAULT_FREQ_HZ 1000U
#define CONFIG_GPIO_LOGICAL_TO_HW {10, 1, 0, 23, 4, 5, 6, 24}
#define CONFIG_BUTTON_PIN 28
#define CONFIG_GPIO_POWER_3V3_PIN 8
#define CONFIG_GPIO_POWER_5V_PIN 9
#define CONFIG_BUZZER_PIN 12

/* Product UART id -> hardware UART port number (controller 0 reserved for console). */
#define CONFIG_UART_ID_TO_NUM {1}
#define CONFIG_UART_RX_BUF_BYTES 4096
#define CONFIG_UART_MAX_PAYLOAD_BYTES 2048

#define CONFIG_SCRIPT_MAX_CALLS 256
#define CONFIG_SCRIPT_MAX_TIMEOUT_US (10ULL * 1000 * 1000)
#define CONFIG_SCRIPT_MAX_SOURCE_BYTES 8192
#define CONFIG_SCRIPT_LUA_HEAP_BYTES (64 * 1024)
#define CONFIG_SCRIPT_STACK_BYTES 8192
#define CONFIG_SCRIPT_WAITER_STACK_BYTES 4096
#define CONFIG_SCRIPT_MAX_OUTPUT_BYTES 4096

#endif
